<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-597958c53c93a607afca12fd375c57ed.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.26">

  <meta name="author" content="Masaki EGUCHI, Ph.D.">
  <title>Linguistic Data Analysis II (Summer 2026) – Session 6: Evaluation Metrics</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-8a0cddfb59198b3e6cf1879f0c3c0dad.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="center quarto-title-block">
  <p class="kicker">Linguistic Data Analysis II · Day 2</p>
  <h1 class="title">Session 6: Evaluation Metrics</h1>
  <p class="subtitle">Day 2 · Annotation, Gold Standards &amp; Metrics (2-3)</p>
  <div class="title-meta">
    <p class="author">Masaki EGUCHI, Ph.D.</p>
    <p class="institute">Tohoku University · Summer 2026</p>
  </div>
</section>
<section class="slide level2">

<!-- Executes S4's phases ④⑤ as TWO PASSES over the same CEFR-SP data:
       pass 1 = binary ("is it advanced?"), metrics built from scratch, steps 1–10;
       pass 2 = the real 6-class task, scikit-learn.
     SURFACE DIVISION (differs from S5 on purpose): this deck carries BOTH the concept
     AND the implementation — every line of pass-1 code is on a slide with what it prints.
     The notebook (day2-s6_evaluation_metrics.ipynb) is the follow-along: students type or
     copy each chunk and run it. So every printed value here MUST equal what the matching
     notebook cell prints. All numbers below are computed from the committed
     gold/cefr_sentences.json + gold/predictions_day2.json — do not edit them by hand.
     Cross-reference BY STEP NUMBER, never by slide number. -->
</section>
<section>
<section id="session-6-evaluation-metrics" class="title-slide slide level1 center">
<h1>Session 6: Evaluation Metrics</h1>

</section>
<section id="agenda" class="slide level2">
<h2>📋 Agenda</h2>
<p>Yesterday’s question was <em>“do two people agree?”</em> Today’s is <strong>“is the model any good?”</strong> — same tools, one column swapped.</p>
<ul>
<li><strong>Pass 1 — you build the metrics.</strong> TP/FP/FN/TN → confusion matrix → precision, recall, F1 → Cohen’s κ. No libraries.</li>
<li><strong>Pass 2 — scikit-learn does it at scale</strong>, on all six CEFR levels at once.</li>
<li><strong>作戦会議</strong> — turn today’s mechanics onto your own project track.</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>The code is on these slides.</strong> You type it in Colab as we go — one small piece at a time, running each piece before the next. If you fall behind, copy the code from the slide and continue from there.</p>
</div>
</div>
</div>
</section>
<section id="learning-objectives" class="slide level2 smaller">
<h2>🎯 Learning Objectives</h2>
<p>By the end of this session, you will be able to:</p>
<ul>
<li><strong>Classify one item</strong> as <strong>TP · FP · FN · TN</strong>, and write that decision as an <code>if</code>/<code>elif</code>.</li>
<li><strong>Loop and tally</strong> — one outcome per item, then the four counts.</li>
<li><strong>Confusion matrix</strong> — build it from those counts and read it.</li>
<li><strong>Precision, recall, F1, Cohen’s κ</strong> — compute each from scratch and say what it answers.</li>
<li><strong>scikit-learn</strong> — <code>classification_report</code>, <code>confusion_matrix</code>, <code>cohen_kappa_score</code> on a 6-class task.</li>
<li><strong>Interpretation</strong> — say what a high or low score does and <strong>does not</strong> tell you.</li>
</ul>
</section></section>
<section>
<section id="where-we-are" class="title-slide slide level1 center">
<h1>Where we are</h1>

</section>
<section id="recap-the-define-first-workflow" class="slide level2 smaller">
<h2>Recap: the define-first workflow</h2>
<p>S4 laid out five phases. S5 ran ③ — you built a gold standard. Today you evaluate a model against it.</p>
<ul>
<li>① Define the task · ② Operationalize · ③ Build the gold standard <em>(yesterday)</em></li>
<li><strong>④ Target = human agreement</strong> ← the highest score you can realistically expect, set by your κ from S5</li>
<li><strong>⑤ Evaluate the model against gold</strong> ← <strong>today</strong></li>
</ul>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The same tool, one column swapped</strong></p>
</div>
<div class="callout-content">
<p>In <strong>S5</strong> you compared <strong>annotator A vs.&nbsp;annotator B</strong> → <em>inter-annotator agreement</em>. Today you compare <strong>gold vs.&nbsp;model</strong> → <em>model evaluation</em>. <strong>Identical formulas. Identical code.</strong> Only the second column changed.</p>
</div>
</div>
</div>
</div>
</section>
<section id="what-you-already-know-from-s4" class="slide level2 smaller">
<h2>What you already know from S4</h2>
<p>You have already met all of today’s math. Today you <em>implement</em> it.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>The four cells</strong> — rows = gold, columns = prediction</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Pred <strong>+</strong></th>
<th style="text-align: center;">Pred <strong>−</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gold <strong>+</strong></td>
<td style="text-align: center;"><strong>TP</strong></td>
<td style="text-align: center;"><strong>FN</strong></td>
</tr>
<tr class="even">
<td>Gold <strong>−</strong></td>
<td style="text-align: center;"><strong>FP</strong></td>
<td style="text-align: center;"><strong>TN</strong></td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:50%;">
<p><strong>The formulas</strong></p>
<p><span class="math display">\[P = \frac{TP}{TP+FP} \qquad R = \frac{TP}{TP+FN}\]</span></p>
<p><span class="math display">\[F_1 = 2\cdot\frac{P\cdot R}{P+R} \qquad \kappa = \frac{p_o - p_e}{1 - p_e}\]</span></p>
</div></div>
<div class="fragment">
<p><em>Knowing a formula and being able to compute it are different things. After today, you can explain how every number in your project was calculated.</em></p>
</div>
</section></section>
<section>
<section id="how-today-works-two-passes" class="title-slide slide level1 center">
<h1>How today works — two passes</h1>

</section>
<section id="the-same-data-asked-twice" class="slide level2 smaller">
<h2>The same data, asked twice</h2>
<p>We use the <strong>CEFR-SP</strong> set from S5: 72 sentences, 12 per level, and a model’s frozen predictions for each.</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Pass 1 — you build it</strong></th>
<th><strong>Pass 2 — scikit-learn</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Question</strong></td>
<td>“Is this sentence <strong>advanced</strong>?” (yes/no)</td>
<td>“Which level — A1…C2?”</td>
</tr>
<tr class="even">
<td><strong>Cells to track</strong></td>
<td><strong>4</strong></td>
<td><strong>36</strong></td>
</tr>
<tr class="odd">
<td><strong>Tools</strong></td>
<td><code>for</code>, <code>if</code>, dictionaries</td>
<td><code>classification_report</code>, <code>confusion_matrix</code>, <code>cohen_kappa_score</code></td>
</tr>
<tr class="even">
<td><strong>You learn</strong></td>
<td><em>where the numbers come from</em></td>
<td><em>how to get them at scale</em></td>
</tr>
</tbody>
</table>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Why binary first</strong></p>
</div>
<div class="callout-content">
<p>Four cells are small enough to count by hand. Everything you build in pass 1 is <strong>exactly</strong> what scikit-learn does in pass 2 — six times, once per level.</p>
</div>
</div>
</div>
</div>
</section>
<section id="today-runs-on-frozen-predictions" class="slide level2 smaller">
<h2>Today runs on <em>frozen</em> predictions</h2>
<p>No API key, no live model. The model was run <strong>once</strong>, offline, and its answers committed to a file.</p>
<ul>
<li><strong>Day 1</strong> — you saw the model’s answers <strong>change from run to run</strong>.</li>
<li><strong>Problem</strong> — that variation makes it impossible to tell a coding mistake from a model difference.</li>
<li><strong>So today</strong> — <strong>everyone’s precision, recall, F1 and κ are identical</strong>. If your number differs from the slide, you have a bug in your code.</li>
</ul>
<p><em>You run the model yourself, live, from Day 3 on.</em></p>
</section>
<section id="load-the-data-first" class="slide level2 smaller">
<h2>Load the data first</h2>
<p>Every evaluation begins by <strong>loading the two things it compares</strong> — the gold standard and the model’s predictions. This is a step of its own; the confusion matrix later is built from exactly what you load here.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a></a>gold <span class="op">=</span> load_gold(GOLD_URL)                        <span class="co"># 72 records: {id, text, label}</span></span>
<span id="cb1-2"><a></a>predictions <span class="op">=</span> load_predictions(PREDICTIONS_URL)   <span class="co"># one level per item, same order</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="fragment">
<p>Both are plain lists in the <strong>same order</strong>: <code>predictions[i]</code> is the model’s answer for <code>gold[i]</code>.</p>
</div>
</section></section>
<section>
<section id="pass-1-step-1-collapse-to-one-yesno-question" class="title-slide slide level1 center">
<h1>Pass 1 · Step 1 — collapse to one yes/no question</h1>

</section>
<section id="six-levels-one-question" class="slide level2 smaller">
<h2>Six levels → one question</h2>
<p>CEFR has six levels. For pass 1 we ask <strong>one</strong> thing:</p>
<blockquote>
<p><strong>Is this sentence <em>advanced</em> — C1 or C2?</strong></p>
</blockquote>
<ul>
<li><code>"yes"</code> = C1 or C2 → this is our <strong>positive class</strong></li>
<li><code>"no"</code> = A1, A2, B1, B2</li>
</ul>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Choosing the positive class is a decision, not a technicality.</strong> “Precision” and “recall” are always <em>about the positive class</em>. Change what counts as positive and every number changes. In your project, say out loud which class is positive before you report a score.</p>
</div>
</div>
</div>
</div>
</section>
<section id="build-the-twelve-from-what-you-loaded" class="slide level2 smaller">
<h2>Build the twelve from what you loaded</h2>
<p>The twelve rows are <strong>not typed in</strong> — they are sliced from the <code>gold</code> and <code>predictions</code> you just loaded (ids 17–28) and collapsed to yes/no. Same <code>for</code>, <code>if</code>, dictionaries as the rest of pass 1:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a></a>ADVANCED <span class="op">=</span> [<span class="st">"C1"</span>, <span class="st">"C2"</span>]          <span class="co"># the levels that count as "yes"</span></span>
<span id="cb2-2"><a></a></span>
<span id="cb2-3"><a></a>gold_12 <span class="op">=</span> gold[<span class="dv">16</span>:<span class="dv">28</span>]            <span class="co"># positions 16–27 → ids 17–28</span></span>
<span id="cb2-4"><a></a>pred_12 <span class="op">=</span> predictions[<span class="dv">16</span>:<span class="dv">28</span>]</span>
<span id="cb2-5"><a></a></span>
<span id="cb2-6"><a></a>items <span class="op">=</span> []</span>
<span id="cb2-7"><a></a>i <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb2-8"><a></a><span class="cf">for</span> g <span class="kw">in</span> gold_12:</span>
<span id="cb2-9"><a></a>    p <span class="op">=</span> pred_12[i]               <span class="co"># the model's answer for that same sentence</span></span>
<span id="cb2-10"><a></a>    <span class="cf">if</span> g[<span class="st">"label"</span>] <span class="kw">in</span> ADVANCED:</span>
<span id="cb2-11"><a></a>        gold_answer <span class="op">=</span> <span class="st">"yes"</span></span>
<span id="cb2-12"><a></a>    <span class="cf">else</span>:</span>
<span id="cb2-13"><a></a>        gold_answer <span class="op">=</span> <span class="st">"no"</span></span>
<span id="cb2-14"><a></a>    <span class="cf">if</span> p <span class="kw">in</span> ADVANCED:</span>
<span id="cb2-15"><a></a>        pred_answer <span class="op">=</span> <span class="st">"yes"</span></span>
<span id="cb2-16"><a></a>    <span class="cf">else</span>:</span>
<span id="cb2-17"><a></a>        pred_answer <span class="op">=</span> <span class="st">"no"</span></span>
<span id="cb2-18"><a></a>    items.append({<span class="st">"id"</span>: g[<span class="st">"id"</span>], <span class="st">"text"</span>: g[<span class="st">"text"</span>],</span>
<span id="cb2-19"><a></a>                  <span class="st">"gold"</span>: gold_answer, <span class="st">"pred"</span>: pred_answer})</span>
<span id="cb2-20"><a></a>    i <span class="op">=</span> i <span class="op">+</span> <span class="dv">1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="twelve-sentences-count-them-yourself" class="slide level2 smaller">
<h2>Twelve sentences — count them yourself</h2>
<p>The twelve <code>items</code> you just built, with the gold level and the model’s level collapsed to yes/no:</p>
<table class="caption-top">
<colgroup>
<col style="width: 15%">
<col style="width: 53%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>sentence</th>
<th>gold</th>
<th>model</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>17</td>
<td>Newspaper’s revenue from classifieds…</td>
<td>B2 → no</td>
<td>B2 → no</td>
</tr>
<tr class="even">
<td>18</td>
<td>Saffron’s aroma is often described…</td>
<td>C1 → <strong>yes</strong></td>
<td>C1 → <strong>yes</strong></td>
</tr>
<tr class="odd">
<td>19</td>
<td>He died on 26 September 2017 in Paris…</td>
<td>A1 → no</td>
<td>A2 → no</td>
</tr>
<tr class="even">
<td>20</td>
<td>Bat : the bat used by the offense…</td>
<td>B2 → no</td>
<td>B2 → no</td>
</tr>
<tr class="odd">
<td>21</td>
<td>Because oxygen is more electronegative…</td>
<td>C2 → <strong>yes</strong></td>
<td>C1 → <strong>yes</strong></td>
</tr>
<tr class="even">
<td>22</td>
<td>Racing bicycles used for Criteriums…</td>
<td>C1 → <strong>yes</strong></td>
<td>B2 → no</td>
</tr>
<tr class="odd">
<td>23</td>
<td>Harris died on 9 May 2019, at the age…</td>
<td>A1 → no</td>
<td>A2 → no</td>
</tr>
<tr class="even">
<td>24</td>
<td>The first derivative test is used in…</td>
<td>C1 → <strong>yes</strong></td>
<td>B2 → no</td>
</tr>
<tr class="odd">
<td>25</td>
<td>She died on June 9, 2014, at the age…</td>
<td>A1 → no</td>
<td>A2 → no</td>
</tr>
<tr class="even">
<td>26</td>
<td>The forest contains at least 900 plant…</td>
<td>A2 → no</td>
<td>A2 → no</td>
</tr>
<tr class="odd">
<td>27</td>
<td>Cryptobranchids are large, fat salamanders…</td>
<td>C2 → <strong>yes</strong></td>
<td>C1 → <strong>yes</strong></td>
</tr>
<tr class="even">
<td>28</td>
<td>The seven pitches of any diatonic scale…</td>
<td>B2 → no</td>
<td>C1 → <strong>yes</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="your-count" class="slide level2 smaller">
<h2>Your count</h2>
<p>Before any code: <strong>how many TP, FP, FN, TN?</strong> Take a minute with your partner.</p>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">model says <strong>yes</strong></th>
<th style="text-align: center;">model says <strong>no</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>gold <strong>yes</strong></td>
<td style="text-align: center;"><strong>TP = 3</strong></td>
<td style="text-align: center;"><strong>FN = 2</strong></td>
</tr>
<tr class="even">
<td>gold <strong>no</strong></td>
<td style="text-align: center;"><strong>FP = 1</strong></td>
<td style="text-align: center;"><strong>TN = 6</strong></td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<ul>
<li><strong>TP = 3</strong> — rows 18, 21, 27: advanced, and the model said advanced.</li>
<li><strong>FN = 2</strong> — rows 22, 24: advanced (C1), but the model said not advanced.</li>
<li><strong>FP = 1</strong> — row 28: not advanced (B2), but the model said advanced.</li>
<li><strong>TN = 6</strong> — the rest: not advanced, and the model said not advanced.</li>
</ul>
<p><strong>Keep these four numbers.</strong> Everything else today is arithmetic on them, and your code has to reproduce them.</p>
</div>
</section></section>
<section>
<section id="pass-1-step-2-ask-one-item" class="title-slide slide level1 center">
<h1>Pass 1 · Step 2 — ask one item</h1>

</section>
<section id="open-colab-and-look-at-one-item" class="slide level2 smaller">
<h2>Open Colab and look at one item</h2>
<p>The 12 rows you just built are a list of dictionaries — the same <code>{id, text, …}</code> shape you have used since Day 1, with two extra keys:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a></a>item <span class="op">=</span> items[<span class="dv">0</span>]                     <span class="co"># the first of the 12 rows</span></span>
<span id="cb3-2"><a></a><span class="bu">print</span>(item[<span class="st">"gold"</span>], item[<span class="st">"pred"</span>])   <span class="co"># its gold answer, then the model's</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="fragment">
<pre><code>no no</code></pre>
<p>Row 17: the gold says not advanced, and the model says not advanced. Every metric today is computed from pairs like this — <strong>one item, two labels</strong>.</p>
</div>
</section>
<section id="ask-it-the-first-question" class="slide level2 smaller">
<h2>Ask it the first question</h2>
<p>Is this item a <strong>true positive</strong>? That means <em>both</em> labels are <code>"yes"</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a></a><span class="co"># `and` means BOTH sides have to be true:</span></span>
<span id="cb5-2"><a></a><span class="cf">if</span> item[<span class="st">"gold"</span>] <span class="op">==</span> <span class="st">"yes"</span> <span class="kw">and</span> item[<span class="st">"pred"</span>] <span class="op">==</span> <span class="st">"yes"</span>:</span>
<span id="cb5-3"><a></a>    <span class="bu">print</span>(<span class="st">"TP"</span>)     <span class="co"># only runs when both are "yes"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="fragment">
<pre><code></code></pre>
<p><strong>Nothing printed.</strong> This is not a bug. Row 17 is not a TP, and one <code>if</code> can only answer <em>one</em> of the four questions.</p>
</div>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>An <code>if</code> with no <code>else</code> prints nothing when the condition is false. To classify <strong>every</strong> item we need all four questions, and exactly one of them must run.</p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="pass-1-step-3-the-four-branches" class="title-slide slide level1 center">
<h1>Pass 1 · Step 3 — the four branches</h1>

</section>
<section id="the-22-table-written-as-ifelif" class="slide level2 smaller">
<h2>The 2×2 table, written as <code>if</code>/<code>elif</code></h2>
<div class="columns">
<div class="column" style="width:42%;">
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">pred <strong>yes</strong></th>
<th style="text-align: center;">pred <strong>no</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>gold <strong>yes</strong></td>
<td style="text-align: center;"><strong>TP</strong></td>
<td style="text-align: center;"><strong>FN</strong></td>
</tr>
<tr class="even">
<td>gold <strong>no</strong></td>
<td style="text-align: center;"><strong>FP</strong></td>
<td style="text-align: center;"><strong>TN</strong></td>
</tr>
</tbody>
</table>
<p>Four cells, four branches, in the <strong>same order</strong>.</p>
</div><div class="column" style="width:58%;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a></a><span class="co"># checked top to bottom; only the FIRST match runs, so exactly one branch runs:</span></span>
<span id="cb7-2"><a></a><span class="cf">if</span> item[<span class="st">"gold"</span>] <span class="op">==</span> <span class="st">"yes"</span> <span class="kw">and</span> item[<span class="st">"pred"</span>] <span class="op">==</span> <span class="st">"yes"</span>:</span>
<span id="cb7-3"><a></a>    <span class="bu">print</span>(<span class="st">"TP"</span>)      <span class="co"># advanced, and the model said advanced</span></span>
<span id="cb7-4"><a></a><span class="cf">elif</span> item[<span class="st">"gold"</span>] <span class="op">==</span> <span class="st">"no"</span> <span class="kw">and</span> item[<span class="st">"pred"</span>] <span class="op">==</span> <span class="st">"yes"</span>:</span>
<span id="cb7-5"><a></a>    <span class="bu">print</span>(<span class="st">"FP"</span>)      <span class="co"># not advanced, but the model said advanced</span></span>
<span id="cb7-6"><a></a><span class="cf">elif</span> item[<span class="st">"gold"</span>] <span class="op">==</span> <span class="st">"yes"</span> <span class="kw">and</span> item[<span class="st">"pred"</span>] <span class="op">==</span> <span class="st">"no"</span>:</span>
<span id="cb7-7"><a></a>    <span class="bu">print</span>(<span class="st">"FN"</span>)      <span class="co"># advanced, but the model said not advanced</span></span>
<span id="cb7-8"><a></a><span class="cf">else</span>:</span>
<span id="cb7-9"><a></a>    <span class="bu">print</span>(<span class="st">"TN"</span>)      <span class="co"># not advanced, and the model said not advanced</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div></div>
<div class="fragment">
<p><code>elif</code> = <em>“only if none of the above matched.”</em> The branches are checked top to bottom and <strong>exactly one</strong> runs — so every item lands in exactly one cell. The final <code>else</code> needs no condition: if it isn’t TP, FP or FN, it can only be TN.</p>
</div>
</section>
<section id="try-it-on-a-different-row" class="slide level2 smaller">
<h2>Try it on a different row</h2>
<p>Change which item you look at and re-run:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a></a>item <span class="op">=</span> items[<span class="dv">11</span>]          <span class="co"># row 28</span></span>
<span id="cb8-2"><a></a><span class="bu">print</span>(item[<span class="st">"gold"</span>], item[<span class="st">"pred"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>no yes</code></pre>
<div class="fragment">
<p>The gold says not advanced; the model said advanced. Branch 1 fails, branch 2 matches:</p>
<pre><code>FP</code></pre>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Your turn:</strong> find an item that prints <code>FN</code>. <em>(Hint: rows 22 and 24 — the two advanced sentences the model labelled not advanced.)</em></p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="pass-1-step-4-make-it-a-function" class="title-slide slide level1 center">
<h1>Pass 1 · Step 4 — make it a function</h1>

</section>
<section id="twelve-items-one-rule" class="slide level2 smaller">
<h2>Twelve items, one rule</h2>
<p>You are about to ask that same question of all 12 rows. Instead of copying the four branches twelve times, <strong>give them a name once</strong>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a></a><span class="kw">def</span> outcome(gold_label, pred_label):</span>
<span id="cb11-2"><a></a>    <span class="co">"""Which of the four cells does this one item belong to?"""</span></span>
<span id="cb11-3"><a></a>    <span class="cf">if</span> gold_label <span class="op">==</span> <span class="st">"yes"</span> <span class="kw">and</span> pred_label <span class="op">==</span> <span class="st">"yes"</span>:</span>
<span id="cb11-4"><a></a>        <span class="cf">return</span> <span class="st">"TP"</span>      <span class="co"># `return` gives the answer back, instead of printing it</span></span>
<span id="cb11-5"><a></a>    <span class="cf">elif</span> gold_label <span class="op">==</span> <span class="st">"no"</span> <span class="kw">and</span> pred_label <span class="op">==</span> <span class="st">"yes"</span>:</span>
<span id="cb11-6"><a></a>        <span class="cf">return</span> <span class="st">"FP"</span></span>
<span id="cb11-7"><a></a>    <span class="cf">elif</span> gold_label <span class="op">==</span> <span class="st">"yes"</span> <span class="kw">and</span> pred_label <span class="op">==</span> <span class="st">"no"</span>:</span>
<span id="cb11-8"><a></a>        <span class="cf">return</span> <span class="st">"FN"</span></span>
<span id="cb11-9"><a></a>    <span class="cf">else</span>:</span>
<span id="cb11-10"><a></a>        <span class="cf">return</span> <span class="st">"TN"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="fragment">
<p>Two changes from step 3, and only two: it is <strong>wrapped in <code>def</code></strong>, and every <code>print</code> became a <strong><code>return</code></strong>.</p>
</div>
</section>
<section id="print-displays-return-gives-the-value-back" class="slide level2 smaller">
<h2><code>print</code> displays · <code>return</code> gives the value back</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a></a><span class="bu">print</span>(outcome(<span class="st">"yes"</span>, <span class="st">"no"</span>))     <span class="co"># gold said advanced, model said not advanced</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="fragment">
<pre><code>FN</code></pre>
</div>
<div class="fragment">
<ul>
<li><strong><code>print</code></strong> — displays a value on the screen; the value is not kept.</li>
<li><strong><code>return</code></strong> — gives the value back to the code that called the function, so you can <strong>store it and count it</strong>. Step 5 needs this.</li>
</ul>
</div>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>Test it by hand before you use it.</strong> <code>outcome("yes", "no")</code> — gold says advanced, model said not advanced → <code>FN</code> ✓. Try all four combinations against the table. Do not use a function you have not tested.</p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="pass-1-step-5-loop-and-store-every-decision" class="title-slide slide level1 center">
<h1>Pass 1 · Step 5 — loop, and store every decision</h1>

</section>
<section id="one-outcome-per-sentence" class="slide level2 smaller">
<h2>One outcome per sentence</h2>
<p>Now run that function over all 12 rows and <strong>keep</strong> the answers — the same “build a list in a loop” pattern you wrote on Day 1:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a></a>decisions <span class="op">=</span> []                     <span class="co"># start empty; the loop adds to it</span></span>
<span id="cb14-2"><a></a><span class="cf">for</span> item <span class="kw">in</span> items:                 <span class="co"># one pass per row of the table</span></span>
<span id="cb14-3"><a></a>    decisions.append(outcome(item[<span class="st">"gold"</span>], item[<span class="st">"pred"</span>]))   <span class="co"># add its outcome</span></span>
<span id="cb14-4"><a></a></span>
<span id="cb14-5"><a></a><span class="bu">print</span>(decisions)                   <span class="co"># 12 outcomes, in the table's order</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="fragment">
<pre><code>['TN', 'TP', 'TN', 'TN', 'TP', 'FN', 'TN', 'FN', 'TN', 'TN', 'TP', 'FP']</code></pre>
</div>
<div class="fragment">
<p>Twelve items in, twelve outcomes out — <strong>in the same order as the table</strong>. Position 6 is <code>'FN'</code>: row 22, the racing-bicycle sentence the model labelled not advanced.</p>
</div>
</section>
<section id="why-store-them-rather-than-just-count" class="slide level2 smaller">
<h2>Why store them, rather than just count?</h2>
<p>We could have counted as we went. We keep the list because <strong>the list records every individual decision</strong>.</p>
<ul>
<li><strong>A metric is a summary.</strong> <code>decisions</code> is what is being summarised, and you can always return to it.</li>
<li><strong>Each <code>'FN'</code> and <code>'FP'</code></strong> points to a <strong>specific sentence</strong> you can read and discuss.</li>
<li><strong>That is error analysis</strong> — the source of your research questions: <em>is this the model’s error, or a problem in my scheme?</em></li>
</ul>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Later today <code>show_errors()</code> does exactly this for you on the 6-class task — it selects the items the model got wrong and prints them. You have just written the same logic yourself.</p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="pass-1-step-6-tally-the-outcomes" class="title-slide slide level1 center">
<h1>Pass 1 · Step 6 — tally the outcomes</h1>

</section>
<section id="count-the-four-outcomes" class="slide level2 smaller">
<h2>Count the four outcomes</h2>
<p>This is Day 1’s <code>count_labels</code> exercise, run on a new list:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a></a>tally <span class="op">=</span> {}                         <span class="co"># a dict: outcome -&gt; how many times</span></span>
<span id="cb16-2"><a></a><span class="cf">for</span> d <span class="kw">in</span> decisions:                <span class="co"># d is "TP", "FP", "FN" or "TN"</span></span>
<span id="cb16-3"><a></a>    tally[d] <span class="op">=</span> tally.get(d, <span class="dv">0</span>) <span class="op">+</span> <span class="dv">1</span>   <span class="co"># count so far (0 if new), plus one</span></span>
<span id="cb16-4"><a></a></span>
<span id="cb16-5"><a></a><span class="bu">print</span>(tally)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="fragment">
<pre><code>{'TN': 6, 'TP': 3, 'FN': 2, 'FP': 1}</code></pre>
</div>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><code>tally.get(d, 0)</code> means <em>“how many so far — and if you’ve never seen this one, start from 0.”</em> Without the <code>.get</code>, the very first <code>'TN'</code> would crash, because <code>tally["TN"]</code> does not exist yet.</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Compare to the numbers you counted by hand in step 1: TP = 3, FP = 1, FN = 2, TN = 6.</strong> They match: your code reproduces your hand count.</p>
</div>
</section></section>
<section>
<section id="pass-1-step-7-the-confusion-matrix" class="title-slide slide level1 center">
<h1>Pass 1 · Step 7 — the confusion matrix</h1>

</section>
<section id="the-tally-arranged" class="slide level2 smaller">
<h2>The tally, arranged</h2>
<p>A confusion matrix is <strong>not a new calculation</strong>. It is those same four numbers, put in a square so you can <em>see</em> them:</p>
<div class="columns">
<div class="column" style="width:45%;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a></a>show_2x2(tally)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>          pred yes  pred no
gold yes         3        2
gold no          1        6</code></pre>
</div><div class="column" style="width:55%;">
<ul>
<li><strong>Diagonal</strong> (3 and 6) — everything the model got right: 9 of 12.</li>
<li><strong>Off-diagonal</strong> (2 and 1) — everything it got wrong, <strong>separated by direction</strong>.</li>
<li><strong>Two FN, one FP</strong> — two advanced sentences called not advanced, one non-advanced sentence called advanced. A single accuracy figure would hide that difference.</li>
</ul>
</div></div>
<div class="fragment">
<p><strong>Look at the matrix before you compute anything.</strong> Where the errors fall is the finding; the metrics only put a number on it.</p>
</div>
</section>
<section id="row-totals-column-totals" class="slide level2 smaller">
<h2>Row totals, column totals</h2>
<p>The margins matter — you need them for κ in step 9:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">pred <strong>yes</strong></th>
<th style="text-align: center;">pred <strong>no</strong></th>
<th style="text-align: center;"><strong>total</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>gold <strong>yes</strong></td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><strong>5</strong> ← the gold set has 5 advanced sentences</td>
</tr>
<tr class="even">
<td>gold <strong>no</strong></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;"><strong>7</strong></td>
</tr>
<tr class="odd">
<td><strong>total</strong></td>
<td style="text-align: center;"><strong>4</strong></td>
<td style="text-align: center;"><strong>8</strong></td>
<td style="text-align: center;"><strong>12</strong></td>
</tr>
</tbody>
</table>
<div class="fragment">
<ul>
<li><strong>Rows</strong> = what the gold says. <strong>Columns</strong> = what the model says.</li>
<li>Gold called 5 sentences advanced; the model called only <strong>4</strong>. It applies the positive label slightly less often than the gold data does.</li>
<li>This pattern becomes much clearer in pass 2.</li>
</ul>
</div>
</section></section>
<section>
<section id="pass-1-step-8-precision-recall-f1" class="title-slide slide level1 center">
<h1>Pass 1 · Step 8 — precision, recall, F1</h1>

</section>
<section id="precision-of-what-it-called-advanced-how-much-was-correct" class="slide level2 smaller">
<h2>Precision — of what it called advanced, how much was correct?</h2>
<p><strong>Numbers first</strong>, so you can check it on paper:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a></a><span class="bu">print</span>(<span class="dv">3</span> <span class="op">/</span> (<span class="dv">3</span> <span class="op">+</span> <span class="dv">1</span>))            <span class="co"># TP / (TP + FP)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>0.75</code></pre>
<div class="fragment">
<p><strong>Same thing, read off the tally</strong> — so it survives a change of data:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a></a><span class="bu">print</span>(tally[<span class="st">"TP"</span>] <span class="op">/</span> (tally[<span class="st">"TP"</span>] <span class="op">+</span> tally[<span class="st">"FP"</span>]))    <span class="co"># the same, from the tally</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>0.75</code></pre>
</div>
<div class="fragment">
<p>Of the 4 sentences the model <em>called</em> advanced, 3 really were. <strong>Precision = 0.75.</strong></p>
</div>
</section>
<section id="precision-now-as-a-function" class="slide level2 smaller">
<h2>Precision — now as a function</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a></a><span class="kw">def</span> precision(tally):</span>
<span id="cb24-2"><a></a>    <span class="co">"""Of everything CALLED advanced, how much really was?  TP / (TP + FP)"""</span></span>
<span id="cb24-3"><a></a>    tp <span class="op">=</span> tally.get(<span class="st">"TP"</span>, <span class="dv">0</span>)      <span class="co"># .get(..., 0) so a missing count reads as 0</span></span>
<span id="cb24-4"><a></a>    fp <span class="op">=</span> tally.get(<span class="st">"FP"</span>, <span class="dv">0</span>)</span>
<span id="cb24-5"><a></a>    <span class="cf">if</span> tp <span class="op">+</span> fp <span class="op">==</span> <span class="dv">0</span>:             <span class="co"># the model never said "yes" at all</span></span>
<span id="cb24-6"><a></a>        <span class="cf">return</span> <span class="fl">0.0</span>               <span class="co"># no correct positives, and no division by zero</span></span>
<span id="cb24-7"><a></a>    <span class="cf">return</span> tp <span class="op">/</span> (tp <span class="op">+</span> fp)        <span class="co"># correct positives, over all positive predictions</span></span>
<span id="cb24-8"><a></a></span>
<span id="cb24-9"><a></a><span class="bu">print</span>(<span class="bu">round</span>(precision(tally), <span class="dv">3</span>))   <span class="co"># round to 3 decimal places</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="fragment">
<pre><code>0.75</code></pre>
</div>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Always guard the denominator</strong></p>
</div>
<div class="callout-content">
<p>If a model never predicts the positive class, <code>TP + FP</code> is <strong>0</strong> and Python raises <code>ZeroDivisionError</code>. Returning <code>0.0</code> records that there were no correct positive predictions. Every metric you write today needs this guard.</p>
</div>
</div>
</div>
</div>
</section>
<section id="recall-your-turn" class="slide level2 smaller">
<h2>Recall — your turn</h2>
<p>Recall asks the <strong>other</strong> question: <em>of everything that truly was advanced, how much did we identify?</em></p>
<p><span class="math display">\[R = \frac{TP}{TP + FN}\]</span></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a></a><span class="kw">def</span> recall(tally):</span>
<span id="cb26-2"><a></a>    <span class="co">"""Of everything that TRULY was advanced, how much did we identify?"""</span></span>
<span id="cb26-3"><a></a>    tp <span class="op">=</span> tally.get(<span class="st">"TP"</span>, <span class="dv">0</span>)</span>
<span id="cb26-4"><a></a>    fn <span class="op">=</span> tally.get(<span class="st">"FN"</span>, <span class="dv">0</span>)       <span class="co"># ← the only real change</span></span>
<span id="cb26-5"><a></a>    <span class="cf">if</span> tp <span class="op">+</span> fn <span class="op">==</span> <span class="dv">0</span>:              <span class="co"># nothing was truly advanced, so there is nothing to find</span></span>
<span id="cb26-6"><a></a>        <span class="cf">return</span> <span class="fl">0.0</span></span>
<span id="cb26-7"><a></a>    <span class="cf">return</span> tp <span class="op">/</span> (tp <span class="op">+</span> fn)         <span class="co"># correct positives, over all true positives in the gold</span></span>
<span id="cb26-8"><a></a></span>
<span id="cb26-9"><a></a><span class="bu">print</span>(<span class="bu">round</span>(recall(tally), <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="fragment">
<pre><code>0.6</code></pre>
<p>Three of the five genuinely advanced sentences were found. <strong>Recall = 0.60.</strong></p>
</div>
</section>
<section id="f1-precision-and-recall-in-one-number" class="slide level2 smaller">
<h2>F1 — precision and recall in one number</h2>
<p>Precision and recall move in opposite directions: if the model labels everything positive, recall becomes 1.0 and precision becomes very low. <strong>F1</strong> is the harmonic mean, so a high value on one side cannot compensate for a low value on the other:</p>
<p><span class="math display">\[F_1 = 2 \cdot \frac{P \cdot R}{P + R}\]</span></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb28"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a></a><span class="kw">def</span> f1(tally):</span>
<span id="cb28-2"><a></a>    <span class="co">"""Harmonic mean of precision and recall."""</span></span>
<span id="cb28-3"><a></a>    p <span class="op">=</span> precision(tally)         <span class="co"># reuse the function you just wrote</span></span>
<span id="cb28-4"><a></a>    r <span class="op">=</span> recall(tally)            <span class="co"># ...and the other one</span></span>
<span id="cb28-5"><a></a>    <span class="cf">if</span> p <span class="op">+</span> r <span class="op">==</span> <span class="dv">0</span>:               <span class="co"># both zero — nothing to average</span></span>
<span id="cb28-6"><a></a>        <span class="cf">return</span> <span class="fl">0.0</span></span>
<span id="cb28-7"><a></a>    <span class="cf">return</span> <span class="dv">2</span> <span class="op">*</span> p <span class="op">*</span> r <span class="op">/</span> (p <span class="op">+</span> r)   <span class="co"># harmonic mean: a low value on either side lowers it</span></span>
<span id="cb28-8"><a></a></span>
<span id="cb28-9"><a></a><span class="bu">print</span>(<span class="bu">round</span>(precision(tally), <span class="dv">3</span>), <span class="bu">round</span>(recall(tally), <span class="dv">3</span>), <span class="bu">round</span>(f1(tally), <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="fragment">
<pre><code>0.75 0.6 0.667</code></pre>
</div>
</section>
<section id="what-0.75-vs.-0.60-actually-says" class="slide level2 smaller">
<h2>What 0.75 vs.&nbsp;0.60 actually says</h2>
<p>The gap between precision and recall <strong>describes how the model behaves</strong>:</p>
<ul>
<li><strong>Precision 0.75 &gt; Recall 0.60</strong> — the model applies the label <em>advanced</em> less often than the gold data does. When it does apply it, it is usually correct, but it labels some real C1 sentences as B2.</li>
<li><strong>Both errors were C1 → B2</strong> (rows 22, 24) — one level away, not far away.</li>
</ul>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Which error matters more in your project?</strong></p>
</div>
<div class="callout-content">
<p>That is a <strong>research design</strong> question, not a statistics one.</p>
<ul>
<li><strong>Selecting texts for a C1 reading list</strong> — an FN (an advanced sentence you do not find) is more serious; favour recall.</li>
<li><strong>Claiming in a paper which sentences are advanced</strong> — an FP (a sentence wrongly called advanced) is more serious; favour precision.</li>
</ul>
<p>Say which one your project cares about <em>before</em> you report a score.</p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="pass-1-step-9-cohens-κ" class="title-slide slide level1 center">
<h1>Pass 1 · Step 9 — Cohen’s κ</h1>

</section>
<section id="why-accuracy-isnt-enough" class="slide level2 smaller">
<h2>Why accuracy isn’t enough</h2>
<p>Start with the easy number — <strong>observed agreement</strong>, the diagonal over the total:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a></a>n <span class="op">=</span> tally[<span class="st">"TP"</span>] <span class="op">+</span> tally[<span class="st">"FP"</span>] <span class="op">+</span> tally[<span class="st">"FN"</span>] <span class="op">+</span> tally[<span class="st">"TN"</span>]   <span class="co"># all 12 items</span></span>
<span id="cb30-2"><a></a>p_o <span class="op">=</span> (tally[<span class="st">"TP"</span>] <span class="op">+</span> tally[<span class="st">"TN"</span>]) <span class="op">/</span> n   <span class="co"># the diagonal (both agreed), over the total</span></span>
<span id="cb30-3"><a></a><span class="bu">print</span>(<span class="bu">round</span>(p_o, <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="fragment">
<pre><code>0.75</code></pre>
</div>
<div class="fragment">
<p>Gold and model agree on 9 of 12 items. That looks acceptable — but <strong>a model that answered “no” to every item</strong> would score 7/12 without using any information at all. Raw agreement gives a high score to a model that simply predicts the most frequent label.</p>
</div>
</section>
<section id="agreement-expected-by-chance" class="slide level2 smaller">
<h2>Agreement expected by chance</h2>
<p><span class="math inline">\(p_e\)</span> = the agreement two raters would reach <strong>by chance</strong>, given how often each one uses each label. Multiply their rates, label by label — the row and column totals from step 7:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a></a><span class="co"># each line: how often GOLD says it × how often the MODEL says it = chance agreement</span></span>
<span id="cb32-2"><a></a>p_yes <span class="op">=</span> ((tally[<span class="st">"TP"</span>] <span class="op">+</span> tally[<span class="st">"FN"</span>]) <span class="op">/</span> n) <span class="op">*</span> ((tally[<span class="st">"TP"</span>] <span class="op">+</span> tally[<span class="st">"FP"</span>]) <span class="op">/</span> n)</span>
<span id="cb32-3"><a></a>p_no  <span class="op">=</span> ((tally[<span class="st">"FP"</span>] <span class="op">+</span> tally[<span class="st">"TN"</span>]) <span class="op">/</span> n) <span class="op">*</span> ((tally[<span class="st">"FN"</span>] <span class="op">+</span> tally[<span class="st">"TN"</span>]) <span class="op">/</span> n)</span>
<span id="cb32-4"><a></a>p_e   <span class="op">=</span> p_yes <span class="op">+</span> p_no          <span class="co"># chance agreement on "yes" plus chance agreement on "no"</span></span>
<span id="cb32-5"><a></a><span class="bu">print</span>(<span class="bu">round</span>(p_yes, <span class="dv">3</span>), <span class="bu">round</span>(p_no, <span class="dv">3</span>), <span class="bu">round</span>(p_e, <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="fragment">
<pre><code>0.139 0.389 0.528</code></pre>
</div>
<div class="fragment">
<ul>
<li><code>p_yes</code>: gold says yes <strong>5/12</strong> × model says yes <strong>4/12</strong> = 0.139</li>
<li><code>p_no</code>: gold says no <strong>7/12</strong> × model says no <strong>8/12</strong> = 0.389</li>
<li><strong>More than half</strong> the agreement we observed (0.75) is expected by chance alone.</li>
</ul>
</div>
</section>
<section id="κ-agreement-corrected-for-chance" class="slide level2 smaller">
<h2>κ — agreement corrected for chance</h2>
<p><span class="math display">\[\kappa = \frac{p_o - p_e}{1 - p_e}\]</span></p>
<p><em>Of the agreement that chance does not explain, how much did they achieve?</em></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb34"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a></a><span class="co"># observed minus chance agreement (p_o - p_e), over the agreement still available (1 - p_e):</span></span>
<span id="cb34-2"><a></a><span class="bu">print</span>(<span class="bu">round</span>((p_o <span class="op">-</span> p_e) <span class="op">/</span> (<span class="dv">1</span> <span class="op">-</span> p_e), <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="fragment">
<pre><code>0.471</code></pre>
</div>
<div class="fragment">
<div class="columns">
<div class="column" style="width:55%;">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Cohen’s κ</th>
<th style="text-align: left;">Landis &amp; Koch</th>
<th style="text-align: left;">McHugh</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.21–0.40</td>
<td style="text-align: left;">Fair</td>
<td style="text-align: left;">Minimal</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>0.41–0.60</strong></td>
<td style="text-align: left;"><strong>Moderate</strong></td>
<td style="text-align: left;"><strong>Weak</strong></td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.61–0.80</td>
<td style="text-align: left;">Substantial</td>
<td style="text-align: left;">Moderate</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:45%;">
<p><strong>75% agreement → κ = 0.47.</strong></p>
<p>The same gap S4 showed you (80% → κ ≈ 0.52), now computed by your own code.</p>
</div></div>
</div>
</section>
<section id="the-whole-calculation-as-one-function" class="slide level2 smaller">
<h2>The whole calculation as one function</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb36"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a></a><span class="kw">def</span> kappa(tally):</span>
<span id="cb36-2"><a></a>    <span class="co">"""Agreement corrected for chance: (p_o - p_e) / (1 - p_e)."""</span></span>
<span id="cb36-3"><a></a>    n <span class="op">=</span> tally[<span class="st">"TP"</span>] <span class="op">+</span> tally[<span class="st">"FP"</span>] <span class="op">+</span> tally[<span class="st">"FN"</span>] <span class="op">+</span> tally[<span class="st">"TN"</span>]   <span class="co"># every item</span></span>
<span id="cb36-4"><a></a>    p_o <span class="op">=</span> (tally[<span class="st">"TP"</span>] <span class="op">+</span> tally[<span class="st">"TN"</span>]) <span class="op">/</span> n     <span class="co"># agreement we actually observed</span></span>
<span id="cb36-5"><a></a>    p_yes <span class="op">=</span> ((tally[<span class="st">"TP"</span>] <span class="op">+</span> tally[<span class="st">"FN"</span>]) <span class="op">/</span> n) <span class="op">*</span> ((tally[<span class="st">"TP"</span>] <span class="op">+</span> tally[<span class="st">"FP"</span>]) <span class="op">/</span> n)</span>
<span id="cb36-6"><a></a>    p_no <span class="op">=</span> ((tally[<span class="st">"FP"</span>] <span class="op">+</span> tally[<span class="st">"TN"</span>]) <span class="op">/</span> n) <span class="op">*</span> ((tally[<span class="st">"FN"</span>] <span class="op">+</span> tally[<span class="st">"TN"</span>]) <span class="op">/</span> n)</span>
<span id="cb36-7"><a></a>    p_e <span class="op">=</span> p_yes <span class="op">+</span> p_no                        <span class="co"># agreement expected by chance</span></span>
<span id="cb36-8"><a></a>    <span class="cf">if</span> <span class="dv">1</span> <span class="op">-</span> p_e <span class="op">==</span> <span class="dv">0</span>:                          <span class="co"># chance already explains all agreement</span></span>
<span id="cb36-9"><a></a>        <span class="cf">return</span> <span class="fl">0.0</span></span>
<span id="cb36-10"><a></a>    <span class="cf">return</span> (p_o <span class="op">-</span> p_e) <span class="op">/</span> (<span class="dv">1</span> <span class="op">-</span> p_e)            <span class="co"># the share of the remaining agreement achieved</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>This is yesterday’s function</strong></p>
</div>
<div class="callout-content">
<p>Nothing in <code>kappa()</code> knows whether column two came from <strong>your partner</strong> or <strong>a model</strong>. That is why S5’s agreement number and today’s evaluation number are the same statistic: <strong>κ measures two label columns, whoever produced them.</strong></p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="pass-1-step-10-check-yourself-against-scikit-learn" class="title-slide slide level1 center">
<h1>Pass 1 · Step 10 — check yourself against scikit-learn</h1>

</section>
<section id="does-your-code-match-the-library" class="slide level2 smaller">
<h2>Does your code match the library?</h2>
<p>You built a confusion matrix and four metrics by hand. Before trusting them, check them against <code>scikit-learn</code> <strong>on the same twelve items</strong> — it builds the same 2×2 and computes the same numbers, and if yours differ you have a bug. This is the only place <code>scikit-learn</code> enters pass 1:</p>
<pre><code>✅ TP/FP/FN/TN     yours=3/1/2/6  sklearn=3/1/2/6
✅ precision      yours=0.750000  sklearn=0.750000
✅ recall         yours=0.600000  sklearn=0.600000
✅ f1             yours=0.666667  sklearn=0.666667
✅ cohen_kappa    yours=0.470588  sklearn=0.470588
-----------------------------------------------
All 5 checks passed ✅  — your confusion matrix and metrics match scikit-learn.</code></pre>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>This is the point of pass 1</strong></p>
</div>
<div class="callout-content">
<p><code>sklearn</code> is not doing anything you cannot do. It is doing <strong>exactly what you just wrote</strong>, faster and for every class at once. <strong>Twelve items is enough to learn the mechanics, never enough to judge a model</strong> — so pass 2 hands the full 72 to <code>scikit-learn</code>. From here on, when a report prints <code>0.36</code>, you know precisely which counts produced it.</p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="pass-2-the-real-task-with-scikit-learn" class="title-slide slide level1 center">
<h1>Pass 2 · The real task, with scikit-learn</h1>

</section>
<section id="six-levels-thirty-six-cells" class="slide level2 smaller">
<h2>Six levels, thirty-six cells</h2>
<p>Drop the yes/no simplification. The actual task is the <strong>full ordinal CEFR scale</strong>: <strong>A1 · A2 · B1 · B2 · C1 · C2</strong>. Nothing new is loaded — the <code>gold</code> and <code>predictions</code> from the start already carry the full level; pass 1 only <em>collapsed</em> them to yes/no.</p>
<ul>
<li><strong>4 cells → 36.</strong> Counting by hand is no longer practical.</li>
<li><strong>One positive class at a time</strong> — with six classes you get <strong>six</strong> precisions, <strong>six</strong> recalls, <strong>six</strong> F1s.</li>
<li><strong>The method is unchanged</strong> — to score <code>C1</code>, treat <strong><code>C1</code> as “yes” and all five others as “no”</strong>: pass 1, run six times. This is called <strong>one-vs-rest</strong>, and it is what <code>classification_report</code> does.</li>
</ul>
<div class="fragment">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb38"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a></a><span class="co"># ordered=True: the six levels form a scale, so also report weighted κ</span></span>
<span id="cb38-2"><a></a>evaluate(gold, predictions, ordered<span class="op">=</span><span class="va">True</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>ordered=True</code> states that these labels form a <strong>scale</strong>, which changes which κ you should read. We return to this below.</p>
</div>
</section>
<section id="read-the-report" class="slide level2 smaller">
<h2>Read the report</h2>
<pre><code>              precision    recall  f1-score   support

          A1       0.75      0.25      0.38        12
          A2       0.35      0.58      0.44        12
          B1       0.36      0.33      0.35        12
          B2       0.37      0.58      0.45        12
          C1       0.35      0.50      0.41        12
          C2       1.00      0.08      0.15        12

    accuracy                           0.39        72
   macro avg       0.53      0.39      0.36        72</code></pre>
<div class="fragment">
<ul>
<li><strong>Each row</strong> is one pass-1 run: for <code>C1</code>, TP/FP/FN/TN with C1 as the positive class.</li>
<li><strong><code>support</code></strong> — how many gold items that class has: 12 each, by design.</li>
<li><strong><code>macro avg</code></strong> — the plain average of the six F1s. Every class counts equally <strong>however rare it is</strong>, which is why it is the figure to report for an imbalanced set.</li>
</ul>
</div>
</section>
<section id="accuracy-is-39-now-look-at-how-it-is-wrong" class="slide level2 smaller">
<h2>Accuracy is 39% — now look at <em>how</em> it is wrong</h2>
<p>Before concluding that the model is useless, look at the size of its errors.</p>
<div class="fragment">
<ul>
<li><strong>97% of its answers are within one level</strong> of the gold label.</li>
<li><strong>Only two sentences</strong> in the whole set are two levels away. No answer is further than that.</li>
<li><strong>A model that had not learned the task</strong> would predict C2 for A1 sentences. This one does not.</li>
</ul>
</div>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>“Right idea, imprecise thresholds”</strong> is a completely different failure from <strong>“doesn’t understand the task”</strong> — and no single accuracy number can tell them apart. That is what the confusion matrix is for.</p>
</div>
</div>
</div>
</div>
</section>
<section id="the-confusion-matrix-read-down-the-columns" class="slide level2 smaller">
<h2>The confusion matrix — read <em>down the columns</em></h2>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">pred A1</th>
<th style="text-align: center;">pred A2</th>
<th style="text-align: center;">pred B1</th>
<th style="text-align: center;">pred B2</th>
<th style="text-align: center;">pred C1</th>
<th style="text-align: center;">pred C2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>gold A1</strong></td>
<td style="text-align: center;"><strong>3</strong></td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td><strong>gold A2</strong></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><strong>7</strong></td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td><strong>gold B1</strong></td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;"><strong>4</strong></td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td><strong>gold B2</strong></td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;"><strong>7</strong></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td><strong>gold C1</strong></td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;"><strong>6</strong></td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td><strong>gold C2</strong></td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;"><strong>1</strong></td>
</tr>
<tr class="odd">
<td><strong>column total</strong></td>
<td style="text-align: center;"><strong>4</strong></td>
<td style="text-align: center;"><strong>20</strong></td>
<td style="text-align: center;"><strong>11</strong></td>
<td style="text-align: center;"><strong>19</strong></td>
<td style="text-align: center;"><strong>17</strong></td>
<td style="text-align: center;"><strong>1</strong></td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Rows are gold, so <em>rows</em> tell you what happened to each true level. But read <strong>down the columns</strong> — how often the model <em>says</em> each level. The gold set is <strong>balanced, 12 per level</strong>, so an unbiased rater would use each label about 12 times.</p>
</div>
</section>
<section id="central-tendency-bias" class="slide level2 smaller">
<h2>Central-tendency bias</h2>
<p>The model said <strong>A2 twenty times</strong> and <strong>A1 four times</strong>. It said <strong>C2 exactly once</strong> — in 72 chances.</p>
<div class="fragment">
<ul>
<li><strong>Predictions concentrate in the middle</strong> of the scale; the two ends are used rarely.</li>
<li><strong>Why?</strong> When a rater — human or machine — has to judge something as unclear as “difficulty”, the middle categories are the safest choice.</li>
<li><strong>Same finding as pass 1</strong> — with “advanced” as positive, precision ran ahead of recall (0.75 vs 0.60 on your twelve). <strong>The model under-uses the top of the scale.</strong></li>
</ul>
</div>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>You will meet this tendency in <strong>your own annotation</strong> — and in your teammates’. It is one of the first things to check in a scheme that isn’t reaching acceptable κ.</p>
</div>
</div>
</div>
</div>
</section>
<section id="two-κ-values-same-data" class="slide level2 smaller">
<h2>Two κ values, same data</h2>
<p><code>evaluate(..., ordered=True)</code> printed both, right under the report:</p>
<pre><code>Cohen's kappa            0.267
Cohen's kappa (weighted) 0.849   &lt;- labels are ordered</code></pre>
<div class="fragment">
<p><strong>Plain κ = 0.27</strong> (“fair” / “minimal”) — because plain κ treats <strong>A1 → A2 as exactly as wrong as A1 → C2</strong>.</p>
<p><strong>Quadratic-weighted κ = 0.85</strong> — because CEFR levels are <strong>ordinal</strong>, so an error of one level should count less than an error of five:</p>
<p><span class="math display">\[w_{ij} = \frac{(i-j)^2}{(N-1)^2}\]</span></p>
</div>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Report the one that matches your labels</strong></p>
</div>
<div class="callout-content">
<p>Same predictions, 0.27 or 0.85 depending on a single argument. <strong>Ordered labels → weighted κ. Unordered categories → plain κ.</strong> State which you used and why; a κ reported without that sentence cannot be interpreted. <em>(Arase et al.&nbsp;reported weighted κ = .628 on this task.)</em></p>
</div>
</div>
</div>
</div>
</section>
<section id="error-analysis-the-models-error-or-the-schemes" class="slide level2 smaller">
<h2>Error analysis — the model’s error, or the scheme’s?</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb41"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a></a>errors <span class="op">=</span> show_errors(gold, predictions)   <span class="co"># a table of every item it got wrong</span></span>
<span id="cb41-2"><a></a>errors.head(<span class="dv">15</span>)     <span class="co"># ...or errors[errors["gold"] == "C2"] for the highest level</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>44 errors — too many to read one by one, and you do not need to. <strong>Read about a dozen</strong>, then look closely at the rows where gold is <strong>C2</strong> or <strong>A1</strong>: disagreements concentrate at the two ends of the scale.</p>
<div class="fragment">
<p>For each error you read, ask:</p>
<ol type="1">
<li>Is the <strong>gold</strong> defensible here, or is this genuinely borderline?</li>
<li>Would <strong>you and your partner</strong> have agreed on this sentence?</li>
<li>Would a <strong>better-written scheme</strong> have prevented this error?</li>
</ol>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Remember rows 19, 23 and 25 — the three obituary sentences. In pass 1’s yes/no task the model got all three <em>right</em>. In six classes it labelled every one of them A2 instead of A1. <strong>The question you ask determines which errors you can see.</strong></p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="作戦会議-day-2-team-planning" class="title-slide slide level1 center">
<h1>作戦会議 — Day-2 team planning</h1>

</section>
<section id="apply-todays-session-to-your-own-project" class="slide level2 smaller">
<h2>Apply today’s session to your own project</h2>
<p>Everything this week has used CEFR-SP. Your project uses different data. Spend the next <strong>~12 minutes</strong> with your team adding three things to your <strong>作戦シート</strong>:</p>
<ol type="1">
<li><strong>A draft annotation scheme</strong> — your label set, plus <strong>one line of guideline per label</strong>. (Steps ①②.)</li>
<li><strong>Your gold source</strong> — the provided pool, or one you build yourselves? Who annotates, and how many items? (Step ③.)</li>
<li><strong>The agreement you would accept</strong> — a κ number, decided <strong>now</strong>, before you see any results. Also state <strong>which class is positive</strong>, and whether your labels are <strong>ordered</strong> (→ weighted κ) or not.</li>
</ol>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Teams often skip point 3. A threshold chosen <em>after</em> seeing the number is not a threshold; it is a justification written afterwards.</p>
</div>
</div>
</div>
</div>
</section></section>
<section id="coming-up" class="title-slide slide level1 center">
<h1>Coming up</h1>
<ul>
<li><strong>S7 — Prompt Design</strong> <em>(concept)</em>: the four prompt elements, zero-shot vs.&nbsp;few-shot, and contamination — <strong>why your few-shot examples must never come from the gold set you evaluate against</strong>.</li>
<li><strong>S8–S9</strong>: you write the prompts, run the model live, and evaluate each version with <strong>exactly today’s metrics</strong>. From here on, “did that prompt help?” is a number you can compute.</li>
</ul>
</section>

<section id="any-questions" class="title-slide slide level1 center">
<h1>Any questions?</h1>



</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Linguistic Data Analysis II</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: false,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1100,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/egumasa\.github\.io\/linguistic-data-analysis-II-2026\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
            let selectedAnnoteEl;
            const selectorForAnnotation = ( cell, annotation) => {
              let cellAttr = 'data-code-cell="' + cell + '"';
              let lineAttr = 'data-code-annotation="' +  annotation + '"';
              const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
              return selector;
            }
            const selectCodeLines = (annoteEl) => {
              const doc = window.document;
              const targetCell = annoteEl.getAttribute("data-target-cell");
              const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
              const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
              const lines = annoteSpan.getAttribute("data-code-lines").split(",");
              const lineIds = lines.map((line) => {
                return targetCell + "-" + line;
              })
              let top = null;
              let height = null;
              let parent = null;
              if (lineIds.length > 0) {
                  //compute the position of the single el (top and bottom and make a div)
                  const el = window.document.getElementById(lineIds[0]);
                  top = el.offsetTop;
                  height = el.offsetHeight;
                  parent = el.parentElement.parentElement;
                if (lineIds.length > 1) {
                  const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
                  const bottom = lastEl.offsetTop + lastEl.offsetHeight;
                  height = bottom - top;
                }
                if (top !== null && height !== null && parent !== null) {
                  // cook up a div (if necessary) and position it 
                  let div = window.document.getElementById("code-annotation-line-highlight");
                  if (div === null) {
                    div = window.document.createElement("div");
                    div.setAttribute("id", "code-annotation-line-highlight");
                    div.style.position = 'absolute';
                    parent.appendChild(div);
                  }
                  div.style.top = top - 2 + "px";
                  div.style.height = height + 4 + "px";
                  div.style.left = 0;
                  let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
                  if (gutterDiv === null) {
                    gutterDiv = window.document.createElement("div");
                    gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                    gutterDiv.style.position = 'absolute';
                    const codeCell = window.document.getElementById(targetCell);
                    const gutter = codeCell.querySelector('.code-annotation-gutter');
                    gutter.appendChild(gutterDiv);
                  }
                  gutterDiv.style.top = top - 2 + "px";
                  gutterDiv.style.height = height + 4 + "px";
                }
                selectedAnnoteEl = annoteEl;
              }
            };
            const unselectCodeLines = () => {
              const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
              elementsIds.forEach((elId) => {
                const div = window.document.getElementById(elId);
                if (div) {
                  div.remove();
                }
              });
              selectedAnnoteEl = undefined;
            };
              // Handle positioning of the toggle
          window.addEventListener(
            "resize",
            throttle(() => {
              elRect = undefined;
              if (selectedAnnoteEl) {
                selectCodeLines(selectedAnnoteEl);
              }
            }, 10)
          );
          function throttle(fn, ms) {
          let throttle = false;
          let timer;
            return (...args) => {
              if(!throttle) { // first call gets through
                  fn.apply(this, args);
                  throttle = true;
              } else { // all the others get throttled
                  if(timer) clearTimeout(timer); // cancel #2
                  timer = setTimeout(() => {
                    fn.apply(this, args);
                    timer = throttle = false;
                  }, ms);
              }
            };
          }
            const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
            for (let i=0; i<annoteTargets.length; i++) {
              const annoteTarget = annoteTargets[i];
              const targetCell = annoteTarget.getAttribute("data-target-cell");
              const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
              const contentFn = () => {
                const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
                if (content) {
                  const tipContent = content.cloneNode(true);
                  tipContent.classList.add("code-annotation-tip-content");
                  return tipContent.outerHTML;
                }
              }
              const config = {
                allowHTML: true,
                content: contentFn,
                onShow: (instance) => {
                  selectCodeLines(instance.reference);
                  instance.reference.classList.add('code-annotation-active');
                  window.tippy.hideAll();
                },
                onHide: (instance) => {
                  unselectCodeLines();
                  instance.reference.classList.remove('code-annotation-active');
                },
                maxWidth: 300,
                delay: [50, 0],
                duration: [200, 0],
                offset: [5, 10],
                arrow: true,
                appendTo: function(el) {
                  return el.parentElement.parentElement.parentElement;
                },
                interactive: true,
                interactiveBorder: 10,
                theme: 'light-border',
                placement: 'right',
                popperOptions: {
                  modifiers: [
                  {
                    name: 'flip',
                    options: {
                      flipVariations: false, // true by default
                      allowedAutoPlacements: ['right'],
                      fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
                    },
                  },
                  {
                    name: 'preventOverflow',
                    options: {
                      mainAxis: false,
                      altAxis: false
                    }
                  }
                  ]        
                }      
              };
              window.tippy(annoteTarget, config); 
            }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>